id: rs-14-config-default
language: Rust
severity: warning
rule:
  any:
    - pattern: $T::default()
    - pattern: $T::<$ARGS>::default()
constraints:
  T:
    regex: "Config$"
message: "Config type is initialized through Default::default(). If Config has a load() method, Config::load() should be used to load the configuration"
